// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkixwoanqxdztjnbzjmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhraXh3b2FucXhkenRqbmJ6am1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzkzNDUsImV4cCI6MjA2MjIxNTM0NX0.rrqr-oNb5ahHtzWBCgLpVjJPVwt5eBciOIgKRwiUcng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);